<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="U2IWIN10PLP" name="Wiki" tests="9" failures="1" timestamp="3 May 2019 08:34:33 GMT" time="155.006" errors="0">
  <testcase name="testRegistrationNONDataDriven" time="38.26" classname="com.test.OneTest"/>
  <testcase name="testRegistrationNew" time="29.054" classname="com.test.OneTest"/>
  <testcase name="testRegistrationNew" time="63.702" classname="com.test.OneTest"/>
  <testcase name="atestOne" time="0.001" classname="com.test.TestNGBasics">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.test.TestNGBasics.atestOne(TestNGBasics.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- atestOne -->
  <testcase name="btestOne" time="0.019" classname="com.test.TestNGBasics"/>
  <testcase name="ctestOne" time="0.0" classname="com.test.TestNGBasics"/>
  <testcase name="dtestOne" time="4.001" classname="com.test.TestNGBasics"/>
  <testcase name="etestOne" time="4.002" classname="com.test.TestNGBasics"/>
  <testcase name="ftestOne" time="4.0" classname="com.test.TestNGBasics"/>
</testsuite> <!-- Wiki -->
